feat(attribute-completeness): add functionality to use multiple attributes and combine them to one filter
GIScience/ohsome-quality-api pull request #810
Opened 2024-07-22 13:52 UTC by Gigaszi

…butes and combine them to one filter

Please add the **type of change** as label. If your PR is not ready for review and merge, please add `🚧 ` to the PR title.

### Description
Please add a clear and concise description of what your PR solves.

### Corresponding issue
Closes #

### New or changed dependencies
-

### Checklist
- [ ] I have updated my branch to `main` (e.g. through `git rebase main`)
- [ ] My code follows the [style guide](https://github.com/GIScience/ohsome-quality-api/blob/main/CONTRIBUTING.md#style-guide) and was checked with [pre-commit](https://github.com/GIScience/ohsome-quality-api/blob/main/CONTRIBUTING.md#pre-commit) before committing
- [ ] I have commented my code
- [ ] I have added sufficient unit and integration [tests](https://github.com/GIScience/ohsome-quality-api/blob/main/docs/development_setup.md#tests)
- [ ] I have updated the [CHANGELOG.md](https://github.com/GIScience/ohsome-quality-api/blob/main/CHANGELOG.md)

Please check all finished tasks. If some tasks do not apply to your PR, please cross their text out (by using `~...~`) and remove their checkboxes.

2024-08-01 13:23 UTC, matthiasschaub commented
- [ ] Let's put attribute metadata information also into `/metadata` as with the other metadata.

2024-08-29 12:41 UTC, mmerdes requested changes
review jointly done by @gigaszi, @sfendrich, and @mmerdes

2024-08-29 12:41 UTC, mmerdes commented on ohsome_quality_api/utils/validators.py
> +    all_attributes = [attribute for attribute in valid_attributes_for_topic]
the name all_attributes is misleading - use `valid_attributes_names` instead?

2024-08-29 12:41 UTC, mmerdes commented on tests/integrationtests/api/test_indicators.py
> +@oqapi_vcr.use_cassette
Can we drop the cassette here as there is no remote access to ohsome API?

2024-08-29 12:41 UTC, mmerdes commented on tests/integrationtests/api/test_indicators.py
> +@oqapi_vcr.use_cassette
see above

2024-08-29 12:41 UTC, mmerdes commented on tests/integrationtests/api/test_ohsome_timeout.py
> +# TODO: could/should this be converted to a parameterized test?
will be changed anyway when the report endpoint is removed

2024-08-29 12:54 UTC, mmerdes commented on ohsome_quality_api/utils/validators.py
> +    all_attributes = [attribute for attribute in valid_attributes_for_topic]
fixed

2024-08-29 13:01 UTC, mmerdes commented on tests/integrationtests/api/test_indicators.py
> +@oqapi_vcr.use_cassette
fixed

2024-08-29 13:06 UTC, mmerdes approved these changes
ok

2024-08-29 13:17 UTC, merged